#!/bin/bash
set -e

cd "$(dirname "$0")/.."
DOTFILES_DIR=$(pwd)

for source in **/*.symlink; do
  target="$HOME/.$(basename "$source" .symlink)"
  if [[ ! -L "$target" ]]; then
    ln -sv "$DOTFILES_DIR/$source" "$target"
  fi
done
