#!/usr/bin/env zsh
set -e

cd "$(dirname "$0")/.."
ZSH=$(pwd)

for source in **/*.symlink; do
  target="$HOME/.$(basename "$source" .symlink)"
  if [[ ! -L "$target" ]]; then
    ln -sv "$ZSH/$source" "$target"
  fi
done

curl -sfLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

vim +PlugInstall +PlugClean! +qall
