#!/usr/bin/env zsh
set -e

cd "$(dirname "$0")/.."
ZSH=$(pwd)

for source in **/*.symlink; do
  target="$HOME/.$(basename "$source" .symlink)"
  if [[ ! -L "$target" ]]; then
    ln -sv "$ZSH/$source" "$target"
  fi
done

mkdir -p "$HOME/.vim/bundle"
if [[ ! -d "$HOME/.vim/bundle/Vundle.vim" ]]; then
  echo "Cloning vundle" >&2
  git clone https://github.com/VundleVim/Vundle.vim.git "$HOME/.vim/bundle/Vundle.vim"
fi

vim +PluginInstall +PluginClean! +qall

git config include.path ~/.gitconfig.local
