#!/bin/bash
set -e

cd "$(dirname "$0")/.."
ZSH=$(pwd)

for source in **/*.symlink; do
  target="$HOME/.$(basename "$source" .symlink)"
  if [ -L "$target" ]; then
    if readlink "$target" | grep -q "$ZSH"; then
      rm -v "$target"
    fi
  fi
done
