#!/usr/bin/env bash
set -e

package='dotfiles'
version=$(cd $DOTFILES && git rev-parse --short HEAD && cd -)

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

export PATH="$(abs_dirname "$0"):${PATH}"

command="$1"

case "$command" in
"-v" | "--version" )
  echo "${package}@${version}" >&2
  ;;
"" | "-h" | "--help" )
  echo -e "${package}@${version}\n$($package-help)" >&2
  ;;
* )
  command_path="$(command -v "$package-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "$package: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
